//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComidasYa_Winforms.ComidasYaWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ComidasYaWebService.ComidasYaWebServiceSoap")]
    public interface ComidasYaWebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pNombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ingreso", ReplyAction="*")]
        ComidasYa_Winforms.ComidasYaWebService.IngresoResponse Ingreso(ComidasYa_Winforms.ComidasYaWebService.IngresoRequest request);
        bool Ingreso(string text1, string text2);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ingreso", Namespace="http://tempuri.org/", Order=0)]
        public ComidasYa_Winforms.ComidasYaWebService.IngresoRequestBody Body;
        
        public IngresoRequest() {
        }
        
        public IngresoRequest(ComidasYa_Winforms.ComidasYaWebService.IngresoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IngresoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pNombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pPassword;
        
        public IngresoRequestBody() {
        }
        
        public IngresoRequestBody(string pNombre, string pPassword) {
            this.pNombre = pNombre;
            this.pPassword = pPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ComidasYa_Winforms.ComidasYaWebService.IngresoResponseBody Body;
        
        public IngresoResponse() {
        }
        
        public IngresoResponse(ComidasYa_Winforms.ComidasYaWebService.IngresoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IngresoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IngresoResult;
        
        public IngresoResponseBody() {
        }
        
        public IngresoResponseBody(bool IngresoResult) {
            this.IngresoResult = IngresoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ComidasYaWebServiceSoapChannel : ComidasYa_Winforms.ComidasYaWebService.ComidasYaWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComidasYaWebServiceSoapClient : System.ServiceModel.ClientBase<ComidasYa_Winforms.ComidasYaWebService.ComidasYaWebServiceSoap>, ComidasYa_Winforms.ComidasYaWebService.ComidasYaWebServiceSoap {
        
        public ComidasYaWebServiceSoapClient() {
        }
        
        public ComidasYaWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComidasYaWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComidasYaWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComidasYaWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ComidasYa_Winforms.ComidasYaWebService.IngresoResponse ComidasYa_Winforms.ComidasYaWebService.ComidasYaWebServiceSoap.Ingreso(ComidasYa_Winforms.ComidasYaWebService.IngresoRequest request) {
            return base.Channel.Ingreso(request);
        }
        
        public bool Ingreso(string pNombre, string pPassword) {
            ComidasYa_Winforms.ComidasYaWebService.IngresoRequest inValue = new ComidasYa_Winforms.ComidasYaWebService.IngresoRequest();
            inValue.Body = new ComidasYa_Winforms.ComidasYaWebService.IngresoRequestBody();
            inValue.Body.pNombre = pNombre;
            inValue.Body.pPassword = pPassword;
            ComidasYa_Winforms.ComidasYaWebService.IngresoResponse retVal = ((ComidasYa_Winforms.ComidasYaWebService.ComidasYaWebServiceSoap)(this)).Ingreso(inValue);
            return retVal.Body.IngresoResult;
        }
    }
}
